export const workingDoctrine = [
	'How we work here — read once per session, then follow it:',
	'1. Start with read_latest_messages. Anything addressed to the person you are with, bring to',
	'   them; post their answer on the same goal or task with post_message.',
	'2. Every piece of work is done on a task. Before writing code, answering or changing anything,',
	'   call find_tasks on the project for the matter at hand and work on the task you find. Raise',
	'   one with create_task only when nothing matches: a bug as "FIX: <what is wrong>", anything',
	'   else as a user story (as a…, I want…, so that…) — every top level task is one unless it is',
	'   a bug. Raising it for someone else on the project, name them with requestedBy: the queue',
	'   works what the people using a live project ask for before the owner’s own ideas, and',
	'   leaves projects that are scoping or on hold till last (read_task_queue, from the top).',
	'   Mark it in progress with update_task_status when the work starts. Before the first',
	'   change, read it with read_task and open every file it lists with read_task_attachment:',
	'   those files are part of the ask.',
	'3. Work that changes a repository happens on a branch named for the task, never on the default',
	'   branch. Bring the default branch up to date first (git pull --ff-only); if the working tree',
	'   already holds uncommitted changes, ask the person what they belong to. Branch before the',
	'   first change: fix/<slug> for a FIX, feature/<slug> for a story, or the branch that already',
	'   exists for the task (find_task_by_branch finds the task for a branch you start on). Record',
	'   the branch on the task with set_task_branch as soon as it exists. Commit each verified step',
	'   there, push the branch, and open a pull request into the default branch titled with the',
	'   task (or give the person the compare link); record the pull request with set_task_branch.',
	'   The person merges, and the task is marked done by itself when the pull request merges.',
	'   Never commit on, merge into, rebase or force-push the default branch. This holds in Claude',
	'   Code and in Cowork alike, whether or not a guard is installed.',
	'4. When the work stops, post one message on the task: what changed, the branch and pull request',
	'   it is on, which files or records, the decisions taken and why, and what is left. Then mark',
	'   it done if it is done, or leave it in progress and say what is next. This is the record;',
	'   nothing is deleted on completion.',
	'5. Files the work depends on go on the task, not only in the chat. A file on your own disk — a',
	'   screenshot, an export, or a file the person attached where your workspace keeps a copy —',
	'   goes through grant_task_upload: send it to the link with one HTTP PUT (up to 25 MB, full',
	'   quality), then record_task_upload. attach_file_to_task takes a sourceUrl for anything at a',
	'   public address (up to 25 MB); its contentBase64 is only for a few lines of text you have',
	'   just written. Never type an image or any other file out as base64: it arrives corrupted. A',
	'   file only the person holds — an image they pasted, which you can see but cannot pass on, or',
	'   one your own network will not let you send — they add themselves: call the tool',
	'   show_task_upload_box for the task, and a box appears in the conversation where they drop,',
	'   paste or choose it. Its answer carries a link that does the same wherever no box is drawn.',
	'   An image that arrives before its task exists waits in the project’s image bank instead:',
	'   find_project_images, look with read_project_image, then put it on its task with',
	'   assign_project_image. Name each file for what it is and say what it shows.',
	'6. A task waits on someone only when it needs information from them. A question for another',
	'   person on the project goes on the task or goal as a message naming them, with post_message',
	'   saying who must answer (waitingOn) and whether their Claude can answer on its own or it',
	'   needs them (waitingFor). Their Claude picks it up through read_latest_messages, brings it',
	'   to them, and posts the answer back. Every other message — a work log, an answer, a status —',
	'   waits on nobody. Something a person has to do is not a wait: it is a task assigned to them',
	'   (set_task_assignees), or a subtask of the task it unblocks, and a task held up by another',
	'   goes on hold with a message naming the task it waits for. Never hand the baton to yourself.',
	'   Never relay through a chat app. Details, measures and messages are shown as Markdown: write',
	'   a list as a list, one point to a line.',
	'7. A refactor round is run by the repository’s refactor-round skill (or its end-of-day script)',
	'   when tools/refactor/deploys_since_baseline.sh says one is due. Your Business Today raises',
	'   "REFACTOR: round N" on a project as the reminder every N deploys of its default branch —',
	'   never raise one by hand; change the rhythm on the project instead (update_project_details).',
	'   The round follows rule 3 on its own refactor/round-N branch and ends in a pull request.',
	'8. The repository’s CLAUDE.md carries these rules in full. Where it says more, follow it.'
].join('\n');
